CREATE OR REPLACE VIEW V_PROF
AS
SELECT PROFNO, NAME, EMAIL, HPAGE
FROM T_PROFESSOR;

SELECT * FROM V_PROF;

SELECT TNAME FROM TAB; -- VIEW 확인 가능

-- VIEW 생성시 별도의 컬럼이름을 지정해줄수 있다
CREATE OR REPLACE VIEW V_PROF(PFNO, NM, EM, HP)
AS
SELECT PROFNO, NAME, EMAIL, HPAGE
FROM T_PROFESSOR;

SELECT * FROM V_PROF;

-- #8102
SELECT * FROM T_PROFESSOR;
SELECT * FROM T_DEPARTMENT;

CREATE OR REPLACE VIEW V_PROF_DEPT(교수번호, 교수명, 소속학과명)
AS
SELECT P.PROFNO, P.NAME, D.DNAME 
FROM T_PROFESSOR P, T_DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO;

SELECT * FROM V_PROF_DEPT;

-- #8103
SELECT 
	d.dname "학과명", 
	s.max_height "최대키", 
	s.max_weight "최대몸무게"
FROM 
	(SELECT deptno1, MAX(height) max_height, MAX(weight) max_weight
	FROM t_student
	GROUP BY deptno1) s, 
	t_department d
WHERE 
	s.deptno1 = d.deptno;

-- #8104
SELECT D.DNAME "학과명", A.MAX_HEIGHT "최대키", S.NAME "학생이름", S.HEIGHT "키"
FROM 
	(SELECT DEPTNO1, MAX(HEIGHT) MAX_HEIGHT FROM T_STUDENT GROUP BY DEPTNO1) A,
	T_STUDENT S, T_DEPARTMENT D
WHERE
	S.DEPTNO1 = A.DEPTNO1 AND S.HEIGHT = A.MAX_HEIGHT
	AND S.DEPTNO1 = D.DEPTNO;

-- #8105
SELECT S.GRADE "학년", S.NAME "이름", S.HEIGHT "키", A.AVG_HEIGHT "평균키"
FROM
	(SELECT GRADE, AVG(HEIGHT) AVG_HEIGHT FROM T_STUDENT GROUP BY GRADE) A,
	T_STUDENT S
WHERE 
	A.GRADE = S.GRADE AND S.HEIGHT > A.AVG_HEIGHT
ORDER BY 1;
	