-- #7201
SELECT GRADE "학년", NAME "이름", HEIGHT "키"
FROM T_STUDENT
WHERE (GRADE, HEIGHT) IN (SELECT GRADE, MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE)
-- ORDER BY GRADE ASC;
-- ORDER BY 1 ASC;
ORDER BY "학년" ASC; -- 실행순서가 SELECT 뒤이기 때문에 컬럼의 별명을 사용할 수 있다. 

-- #7202
SELECT P.PROFNO "교수번호", P.NAME "교수명", TO_CHAR(P.HIREDATE, 'YYYY-MM-DD') "입사일", D.BUILD "학과명"
FROM T_PROFESSOR P, T_DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO 
      AND
      (P.DEPTNO, P.HIREDATE) IN (SELECT DEPTNO, MIN(HIREDATE) FROM T_PROFESSOR GROUP BY DEPTNO)
ORDER BY "학과명" ASC;

-- #7203
SELECT NAME "사원명", POST "직급", PAY "연봉"
FROM T_EMP2
WHERE (POST, PAY) IN (SELECT POST, MAX(PAY) FROM T_EMP2 GROUP BY POST)
ORDER BY "연봉";

-- #7204
SELECT D.DNAME "부서명", E.NAME "직원명", E.PAY "연봉"
FROM T_EMP2 E, T_DEPT2 D
WHERE E.DEPTNO = D.DCODE
	  AND
	  E.PAY <ALL (SELECT AVG(PAY) FROM T_EMP2 GROUP BY DEPTNO)
ORDER BY "연봉" ASC;

-- #7205
SELECT A.NAME "사원이름", NVL(A.POST, ' ') "직급", A.PAY "급여"
FROM T_EMP2 A
WHERE A.PAY >= (SELECT AVG(B.PAY) FROM T_EMP2 B WHERE NVL(A.POST, ' ') = NVL(B.POST, ' '));

SELECT AVG(B.PAY) FROM T_EMP2 B WHERE '과장' = B.POST;

-- # 7206
SELECT NAME "사원이름",
	   (SELECT DNAME FROM T_DEPT2 D
	    WHERE E.DEPTNO = D.DCODE) "부서이름"
FROM T_EMP2 E;